export type Column = { name: string; type: string; note?: string };
export type Table = {
  name: string;
  description: string;
  icon: string;
  columns: Column[];
};

export const SCHEMA: Table[] = [
  {
    name: "customers",
    description: "Customer profiles",
    icon: "👤",
    columns: [
      { name: "customer_id", type: "UUID", note: "PK" },
      { name: "first_name", type: "VARCHAR" },
      { name: "last_name", type: "VARCHAR" },
      { name: "email", type: "VARCHAR" },
      { name: "phone", type: "VARCHAR" },
      { name: "signup_date", type: "TIMESTAMP" },
      { name: "country", type: "VARCHAR" },
      { name: "city", type: "VARCHAR" },
      { name: "status", type: "VARCHAR" },
      { name: "created_at", type: "TIMESTAMP" },
    ],
  },
  {
    name: "orders",
    description: "Customer orders",
    icon: "🧾",
    columns: [
      { name: "order_id", type: "UUID", note: "PK" },
      { name: "customer_id", type: "UUID", note: "FK → customers" },
      { name: "order_date", type: "TIMESTAMP" },
      { name: "status", type: "VARCHAR" },
      { name: "subtotal", type: "DECIMAL" },
      { name: "discount_amount", type: "DECIMAL" },
      { name: "tax_amount", type: "DECIMAL" },
      { name: "shipping_amount", type: "DECIMAL" },
      { name: "total_amount", type: "DECIMAL" },
      { name: "shipping_city", type: "VARCHAR" },
      { name: "shipping_country", type: "VARCHAR" },
    ],
  },
  {
    name: "order_items",
    description: "Products per order",
    icon: "📦",
    columns: [
      { name: "order_item_id", type: "UUID", note: "PK" },
      { name: "order_id", type: "UUID", note: "FK → orders" },
      { name: "product_id", type: "UUID", note: "FK → products" },
      { name: "quantity", type: "INTEGER" },
      { name: "unit_price", type: "DECIMAL" },
      { name: "discount_amount", type: "DECIMAL" },
      { name: "total_amount", type: "DECIMAL" },
    ],
  },
  {
    name: "products",
    description: "Product catalog",
    icon: "🏷️",
    columns: [
      { name: "product_id", type: "UUID", note: "PK" },
      { name: "product_name", type: "VARCHAR" },
      { name: "category_id", type: "UUID", note: "FK → categories" },
      { name: "price", type: "DECIMAL" },
      { name: "cost_price", type: "DECIMAL" },
      { name: "stock_quantity", type: "INTEGER" },
      { name: "status", type: "VARCHAR" },
      { name: "created_at", type: "TIMESTAMP" },
    ],
  },
  {
    name: "categories",
    description: "Product categories",
    icon: "📂",
    columns: [
      { name: "category_id", type: "UUID", note: "PK" },
      { name: "category_name", type: "VARCHAR" },
      { name: "description", type: "TEXT" },
      { name: "parent_category_id", type: "UUID" },
    ],
  },
  {
    name: "payments",
    description: "Payment transactions",
    icon: "💳",
    columns: [
      { name: "payment_id", type: "UUID", note: "PK" },
      { name: "order_id", type: "UUID", note: "FK → orders" },
      { name: "customer_id", type: "UUID", note: "FK → customers" },
      { name: "payment_date", type: "TIMESTAMP" },
      { name: "amount", type: "DECIMAL" },
      { name: "payment_method", type: "VARCHAR" },
      { name: "status", type: "VARCHAR" },
      { name: "transaction_id", type: "VARCHAR" },
    ],
  },
  {
    name: "refunds",
    description: "Refund information",
    icon: "↩️",
    columns: [
      { name: "refund_id", type: "UUID", note: "PK" },
      { name: "order_id", type: "UUID", note: "FK → orders" },
      { name: "payment_id", type: "UUID", note: "FK → payments" },
      { name: "customer_id", type: "UUID", note: "FK → customers" },
      { name: "refund_date", type: "TIMESTAMP" },
      { name: "amount", type: "DECIMAL" },
      { name: "reason", type: "VARCHAR" },
      { name: "status", type: "VARCHAR" },
    ],
  },
  {
    name: "customer_visits",
    description: "Website / app visits",
    icon: "🌐",
    columns: [
      { name: "visit_id", type: "UUID", note: "PK" },
      { name: "customer_id", type: "UUID", note: "FK → customers" },
      { name: "visit_date", type: "TIMESTAMP" },
      { name: "session_duration", type: "INTEGER" },
      { name: "device_type", type: "VARCHAR" },
      { name: "source", type: "VARCHAR" },
      { name: "pages_viewed", type: "INTEGER" },
    ],
  },
  {
    name: "reviews",
    description: "Product reviews",
    icon: "⭐",
    columns: [
      { name: "review_id", type: "UUID", note: "PK" },
      { name: "customer_id", type: "UUID", note: "FK → customers" },
      { name: "product_id", type: "UUID", note: "FK → products" },
      { name: "order_id", type: "UUID", note: "FK → orders" },
      { name: "rating", type: "INTEGER" },
      { name: "review_text", type: "TEXT" },
      { name: "review_date", type: "TIMESTAMP" },
      { name: "verified_purchase", type: "BOOLEAN" },
    ],
  },
  {
    name: "customer_support_tickets",
    description: "Support interactions",
    icon: "🎫",
    columns: [
      { name: "ticket_id", type: "UUID", note: "PK" },
      { name: "customer_id", type: "UUID", note: "FK → customers" },
      { name: "order_id", type: "UUID", note: "FK → orders" },
      { name: "created_at", type: "TIMESTAMP" },
      { name: "resolved_at", type: "TIMESTAMP" },
      { name: "category", type: "VARCHAR" },
      { name: "priority", type: "VARCHAR" },
      { name: "status", type: "VARCHAR" },
      { name: "resolution_time_minutes", type: "INTEGER" },
    ],
  },
];